// phx_example/assets/js/svelte/map.svelte
<script lang="ts">
  import { coordFromClick } from "../helpers/coordFromClick";

  let {
    marker,
    onSelectCoord,
  }: {
    marker: [number, number];
    onSelectCoord: (coord: [number, number]) => void;
  } = $props();

  const handleClick = (event) => {
    const coord = coordFromClick(event);
    onSelectCoord(coord);
  };
</script>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<div class="container" onclick={handleClick} aria-label="map">
  <div
    class="marker"
    style="left: {marker[0]}%; top: calc(100% - {marker[1]}%)"
  ></div>
</div>

<style>
  .container {
    width: 200px;
    height: 200px;
    position: relative;
    border: 1px solid slategrey;
    border-radius: 4px;
  }

  .marker {
    width: 32px;
    height: 32px;
    margin-left: -16px;
    margin-top: -16px;
    background: url("https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Svelte_Logo.svg/1702px-Svelte_Logo.svg.png")
      no-repeat 50% 50%;
    background-size: contain;
    position: absolute;
  }
</style>

// phx_example/assets/js/react/map.tsx
import React, { CSSProperties, MouseEventHandler, useRef } from "react";
import { coordFromClick } from "../helpers/coordFromClick";

const Logo = () => (
  <svg
    width="100%"
    height="100%"
    viewBox="-10.5 -9.45 21 18.9"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    color="rgb(26, 114, 151)"
  >
    <circle cx="0" cy="0" r="2" fill="currentColor"></circle>
    <g stroke="currentColor" strokeWidth="1" fill="none">
      <ellipse rx="10" ry="4.5"></ellipse>
      <ellipse rx="10" ry="4.5" transform="rotate(60)"></ellipse>
      <ellipse rx="10" ry="4.5" transform="rotate(120)"></ellipse>
    </g>
  </svg>
);

const markerStyle = (x: number, y: number) => ({
  width: "32px",
  height: "32px",
  marginLeft: "-16px",
  marginTop: "-16px",
  position: "absolute" as CSSProperties["position"],
  left: `${x}%`,
  top: `calc(100% - ${y}%)`,
});

type Props = {
  marker: [number, number];
  onSelectCoord: (coord: { x: number; y: number }) => void;
};

const Map = ({ marker: [x, y], onSelectCoord }: Props) => {
  const handleClick: MouseEventHandler<HTMLElement> = (event) => {
    const [x, y] = coordFromClick(event);
    onSelectCoord({ x, y });
  };

  return (
    <div
      style={{
        width: "200px",
        height: "200px",
        border: "solid 1px slategrey",
        position: "relative",
        borderRadius: 4,
      }}
      onClick={handleClick}
    >
      <div style={markerStyle(x, y)}>
        <Logo />
      </div>
    </div>
  );
};

export default Map;
